FileVersion = 1
Dependencies = {Beefy2D = "*", corlib = "*", curl = "*"}

[Project]
Name = "IDE"
TargetType = "BeefGUIApplication"
StartupObject = "IDE.Program"

[Platform.Windows]
IconFile = "$(ProjectDir)/Resources/Beef.ico"
ManifestFile = "$(ProjectDir)/Resources/IDE.manifest"
Description = "Beef IDE"
Company = "BeefyTech LLC"
Product = "Beef IDE"
Copyright = "Copyright 2019 BeefyTech"
FileVersion = "0.43.6"
ProductVersion = "0000000000000000"

[Configs.Debug.Win32]
TargetName = ""
OtherLinkFlags = ""

[Configs.Debug.Win64]
TargetDirectory = "$(ProjectDir)/dist"
TargetName = "BeefIDE_d"
OtherLinkFlags = "$(LinkFlags) Comdlg32.lib kernel32.lib user32.lib advapi32.lib shell32.lib IDEHelper64_d.lib"
DebugCommandArguments = "-proddir=\"$(ProjectDir)\\..\\BeefBuild\""
DebugWorkingDirectory = "$(ProjectDir)\\.."
EnvironmentVars = ["_NO_DEBUG_HEAP=1"]
PreprocessorMacros = ["DEBUG,HASGIT"]

[Configs.Release.Win32]
TargetName = ""
OtherLinkFlags = ""

[Configs.Release.Win64]
TargetDirectory = "$(ProjectDir)/dist"
TargetName = "BeefIDE"
OtherLinkFlags = "Comdlg32.lib kernel32.lib user32.lib advapi32.lib shell32.lib Beef042RT64.lib IDEHelper64.lib BeefySysLib64.lib"
DebugCommandArguments = "-proddir=C:\\Beef\\IDE\\Tests\\Test1 -test=scripts\\Breakpoints.txt"
DebugWorkingDirectory = "$(ProjectDir)\\dist"
EnvironmentVars = ["z_NO_DEBUG_HEAP=1"]
PreprocessorMacros = ["RELEASE,HASGIT"]

[Configs.Debug2.Win32]
TargetName = ""
OtherLinkFlags = ""

[Configs.Debug2.Win64]
TargetDirectory = "$(ProjectDir)/dist"
TargetName = "BeefIDE_d2"
OtherLinkFlags = "$(LinkFlags) Comdlg32.lib kernel32.lib user32.lib advapi32.lib shell32.lib IDEHelper64_d.lib BeefySysLib64_d.lib wsock32.lib"
BeefLibType = "DynamicDebug"
DebugCommandArguments = "-workspace=C:\\proj\\BeefTest"
DebugWorkingDirectory = "c:\\Beef\\IDE\\Tests\\EmptyTest"
EnvironmentVars = ["_NO_DEBUG_HEAP=1"]

[Configs.Paranoid.Win64]
TargetDirectory = "$(ProjectDir)/dist"
TargetName = "BeefIDE_p"
OtherLinkFlags = "$(LinkFlags) Comdlg32.lib kernel32.lib user32.lib advapi32.lib shell32.lib IDEHelper64_d.lib BeefySysLib64_d.lib wsock32.lib"

[Configs.Paranoid.Win32]
BeefLibType = "Static"

[Configs.Test.Win32]
BeefLibType = "Static"

[Configs.Test.Win64]
BeefLibType = "Static"

[Configs.Debug3.Win64]
TargetDirectory = "$(ProjectDir)/dist"
TargetName = "BeefIDE_d3"
OtherLinkFlags = "$(LinkFlags) Comdlg32.lib kernel32.lib user32.lib advapi32.lib shell32.lib IDEHelper64_d.lib BeefySysLib64_d.lib wsock32.lib"
BeefLibType = "DynamicDebug"
EnvironmentVars = ["_NO_DEBUG_HEAP=1"]
