FileVersion = 1

[Project]
Name = "WasmLaunch"
TargetType = "BeefGUIApplication"
StartupObject = "WasmLaunch.Program"

[Configs.Debug.Win64]
TargetDirectory = "$(WorkspaceDir)\\..\\..\\IDE\\dist"
TargetName = "$(ProjectName)_d"
DebugCommandArguments = "c:\\Beef_website\\Samples\\SpaceGame\\dist\\SpaceGame.html"

[Configs.Release.Win64]
TargetDirectory = "$(WorkspaceDir)\\..\\..\\IDE\\dist"
