FileVersion = 1

[Project]
Name = "curl"
TargetType = "BeefLib"
StartupObject = "Program"

[Configs.Debug.Linux64]
OtherLinkFlags = "$(LinkFlags) -lcurl"

[Configs.Release.Linux64]
OtherLinkFlags = "$(LinkFlags) -lcurl"
