FileVersion = 1
Dependencies = {corlib = "*", Beefy2D = "*", libgit2 = "*"}

[Project]
Name = "BeefLsp"
StartupObject = "BeefLsp.Program"
ProcessorMacros = ["CLI"]

[Configs.Debug.Win64]
TargetDirectory = "$(WorkspaceDir)/../IDE/dist"
TargetName = "$(ProjectName)_d"
OtherLinkFlags = "$(LinkFlags) Comdlg32.lib kernel32.lib user32.lib advapi32.lib shell32.lib IDEHelper64_d.lib Rpcrt4.lib Ole32.lib"
CLibType = "Dynamic"
BeefLibType = "DynamicDebug"

[Configs.Release.Win64]
TargetDirectory = "$(WorkspaceDir)/../IDE/dist"
OtherLinkFlags = "$(LinkFlags) Comdlg32.lib kernel32.lib user32.lib advapi32.lib shell32.lib IDEHelper64.lib"
CLibType = "Dynamic"

[[ProjectFolder.Items]]
Type = "Folder"
Path = "../IDE/src"
Name = "ide"
AutoInclude = true
